name: Build AMIGOpy (unsigned)

on:
  push:
    branches: [ auto_cont ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          python-version: "3.11"
          environment-file: amigo.yml
          activate-environment: amigo

      - name: Upgrade pip
        shell: powershell
        run: python -m pip install --upgrade pip wheel setuptools

      # ---- Build-time Python deps (GUI + API) ----
      - name: Install build dependencies (GUI + API)
        shell: powershell
        run: |
          # Web stack for API
          pip install fastapi uvicorn[standard] starlette pydantic python-multipart
          # Imaging + scientific stack
          pip install SimpleITK nibabel scikit-image scipy tqdm einops packaging
          # MONAI / nnUNet / TotalSegmentator
          pip install monai==1.* nnunetv2
          # CPU-only PyTorch wheels
          pip install --index-url https://download.pytorch.org/whl/cpu torch torchvision
          # TotalSegmentator itself (pulls extras)
          pip install totalsegmentator
          # Freezer
          pip install pyinstaller

      # ---- Build AMIGOpy GUI from your existing spec ----
      - name: PyInstaller (AMIGOpy GUI)
        shell: powershell
        run: pyinstaller Launch_ImGUI.spec

      # ---- Build Segmentator API (bundled) from .spec ----
      # Make sure segmentator_api.spec is in the repo root
      - name: PyInstaller (Segmentator API, OneDir)
        shell: powershell
        run: pyinstaller segmentator_api.spec

      # ---- Build Windows installers via Inno Setup ----
      - name: Install Inno Setup
        shell: powershell
        run: choco install innosetup -y

      # AMIGOpy installer (your existing script)
      - name: Build Windows installer (AMIGOpy)
        shell: powershell
        run: '& "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" compile.iss'

      # Segmentator API installer (SegmentatorAPI.iss)
      - name: Build Windows installer (Segmentator API)
        shell: powershell
        run: '& "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" SegmentatorAPI.iss'

      # ---- Upload artifacts ----
      - name: Upload AMIGOpy installer (unsigned)
        uses: actions/upload-artifact@v4
        with:
          name: AMIGOpy-Installer-unsigned
          path: Output/*.exe
          if-no-files-found: error

      - name: Upload Segmentator API installer (unsigned)
        uses: actions/upload-artifact@v4
        with:
          name: SegmentatorAPI-Installer-unsigned
          path: Output/SegmentatorAPI-Setup.exe
          if-no-files-found: error

      # (Optional) also upload the raw PyInstaller folders for debugging
      - name: Upload PyInstaller dist (GUI)
        uses: actions/upload-artifact@v4
        with:
          name: dist-AMIGOpy
          path: dist/Launch_ImGUI/**
          if-no-files-found: warn

      - name: Upload PyInstaller dist (Segmentator API)
        uses: actions/upload-artifact@v4
        with:
          name: dist-segmentator_api
          path: dist/segmentator_api/**
          if-no-files-found: warn
