name: Build AMIGOpy (GUI + Worker) — unsigned

on:
  push:
    branches: [ auto_cont ]
  workflow_dispatch:

jobs:
  build-amigopy:
    runs-on: windows-latest
    env:
      # Avoid OpenMP runtime clashes (ITK/MKL vs LLVM OMP)
      KMP_DUPLICATE_LIB_OK: "TRUE"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Use the "heavy" env (torch/TS present) so the worker can be frozen.
      # The GUI part will still exclude them per amigopy_all.spec.
      - name: Setup Miniconda (builder env)
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          python-version: "3.11"
          environment-file: amigo.yml
          activate-environment: amigo_api
          auto-update-conda: true

      # If graphviz is in the env and you render DOTs, expose its bin
      - name: Add Graphviz to PATH (conda)
        shell: powershell
        run: echo "$env:CONDA_PREFIX\Library\bin" >> $env:GITHUB_PATH

      - name: Upgrade pip tooling
        shell: powershell
        run: python -m pip install --upgrade pip wheel setuptools

      - name: Ensure PyInstaller
        shell: powershell
        run: pip install pyinstaller

      - name: Build combined dist (GUI + worker)
        shell: powershell
        run: pyinstaller amigopy_all.spec --clean

      - name: Verify combined dist contents
        shell: powershell
        run: |
          if (-not (Test-Path "dist\AMIGOpy\Launch_ImGUI.exe")) { throw "Launch_ImGUI.exe missing" }
          if (-not (Test-Path "dist\AMIGOpy\segmentator_worker.exe")) { throw "segmentator_worker.exe missing" }
          Get-ChildItem -Recurse dist\AMIGOpy | Select-Object -First 40 | Format-List -Property FullName,Length

      - name: Install Inno Setup
        shell: powershell
        run: choco install innosetup -y

      - name: Build AMIGOpy installer (AMIGOpy.iss)
        shell: powershell
        run: '& "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe" AMIGOpy.iss'

      - name: List installer outputs
        shell: powershell
        run: Get-ChildItem -Recurse Output | Format-List -Property FullName,Length

      - name: Upload AMIGOpy installer (unsigned)
        uses: actions/upload-artifact@v4
        with:
          name: AMIGOpy-Installer-unsigned
          path: Output/AMIGOpy-Setup.exe
          if-no-files-found: error
          overwrite: true