name: Build AMIGOpy installer

on:
  push:
    branches:
      - auto_cont
  workflow_dispatch:

jobs:
  build-and-sign-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          python-version: "3.11"
          environment-file: amigo.yml
          activate-environment: amigo

      # Ensure PyInstaller and the API's runtime deps are present in the build env
      - name: Install build dependencies
        shell: powershell
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller uvicorn fastapi starlette pydantic python-multipart

      # 1) Build AMIGOpy (GUI) from your existing .spec
      - name: Run PyInstaller (AMIGOpy GUI)
        shell: powershell
        run: |
          pyinstaller Launch_ImGUI.spec

      # 2) Build Segmentator API (separate onefile exe; no icon)
      - name: Build Segmentator API exe
        shell: powershell
        run: |
          pyinstaller --noconfirm --clean `
            --name segmentator_api `
            --onefile `
            --noconsole `
            --hidden-import uvicorn `
            --hidden-import fastapi `
            --hidden-import starlette `
            --hidden-import multipart `
            segmentator_api\segmentator_api.py

      # 3) Build AMIGOpy Windows installer via Inno Setup
      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Build Windows installer (AMIGOpy)
        run: '& "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" compile.iss'

      # 4) Stage unsigned bundle (folder, not zip)
      - name: Stage unsigned bundle (folder, not zip)
        shell: powershell
        run: |
          if (Test-Path -LiteralPath "unsigned") { Remove-Item -Recurse -Force "unsigned" }
          New-Item -ItemType Directory -Path "unsigned" | Out-Null
          if (!(Test-Path -LiteralPath "Output\mysetup.exe")) { throw "AMIGOpy installer not found at Output\mysetup.exe" }
          if (!(Test-Path -LiteralPath "dist\segmentator_api.exe")) { throw "Segmentator API exe not found at dist\segmentator_api.exe" }
          Copy-Item "Output\mysetup.exe" "unsigned\mysetup.exe"
          Copy-Item "dist\segmentator_api.exe" "unsigned\segmentator_api.exe"

      - name: Upload unsigned bundle artifact (folder)
        id: upload_unsigned_bundle
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-bundle
          path: unsigned/
          if-no-files-found: error

      # 5) Sign with SignPath (it signs both EXEs found in the uploaded artifact)
      - name: Submit bundle to SignPath
        uses: signpath/github-action-submit-signing-request@v1.1
        with:
          api-token: ${{ secrets.SIGNPATH_API_TOKEN }}
          organization-id: ${{ secrets.SIGNPATH_ORGANIZATION_ID }}
          project-slug: ${{ secrets.SIGNPATH_PROJECT_SLUG }}
          signing-policy-slug: ${{ secrets.SIGNPATH_SIGNING_POLICY_SLUG }}
          github-artifact-id: ${{ steps.upload_unsigned_bundle.outputs.artifact-id }}
          wait-for-completion: true
          output-artifact-directory: signed

      # 6) Extract the signed ZIP so we can upload each EXE individually
      - name: Extract signed files
        shell: powershell
        run: |
          if (Test-Path -LiteralPath "signed_extracted") { Remove-Item -Recurse -Force "signed_extracted" }
          New-Item -ItemType Directory -Path "signed_extracted" | Out-Null
          $zip = Get-ChildItem -Path "signed" -Filter *.zip | Select-Object -First 1
          if (-not $zip) { throw "No signed zip found in 'signed' folder." }
          Expand-Archive -Path $zip.FullName -DestinationPath "signed_extracted" -Force
          Get-ChildItem -Path "signed_extracted" -Recurse

      # 7) Upload each signed EXE separately for easy download
      - name: Upload signed AMIGOpy installer
        uses: actions/upload-artifact@v4
        with:
          name: AMIGOpy_installer_signed.exe
          path: signed_extracted/mysetup.exe
          if-no-files-found: error

      - name: Upload signed Segmentator API
        uses: actions/upload-artifact@v4
        with:
          name: Segmentator_API_signed.exe
          path: signed_extracted/segmentator_api.exe
          if-no-files-found: error

      # (Optional) also keep the original signed zip if you want
      - name: Upload signed bundle (zip)
        uses: actions/upload-artifact@v4
        with:
          name: signed-bundle-zip
          path: signed/
