name: Build AMIGOpy (unsigned)

on:
  push:
    branches:
      - auto_cont
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          python-version: "3.11"
          environment-file: amigo.yml
          activate-environment: amigo

      - name: Install build dependencies
        shell: powershell
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller uvicorn fastapi starlette pydantic python-multipart

      # 1) Build AMIGOpy GUI from your existing .spec
      - name: PyInstaller (AMIGOpy GUI)
        shell: powershell
        run: |
          pyinstaller Launch_ImGUI.spec

      # 2) Build Segmentator API as a separate exe
      - name: PyInstaller (Segmentator API)
        shell: powershell
        run: |
          pyinstaller --noconfirm --clean `
            --name segmentator_api `
            --onefile `
            --noconsole `
            --hidden-import uvicorn `
            --hidden-import fastapi `
            --hidden-import starlette `
            --hidden-import multipart `
            segmentator_api\segmentator_api.py

      # 3) Build AMIGOpy Windows installer via Inno Setup (unchanged)
      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Build Windows installer (AMIGOpy)
        run: '& "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" compile.iss'

      # 4) Upload artifacts separately (no signing)
      - name: Upload AMIGOpy installer (unsigned)
        uses: actions/upload-artifact@v4
        with:
          name: AMIGOpy-Installer-unsigned
          path: Output/mysetup.exe
          if-no-files-found: error

      - name: Upload Segmentator API exe (unsigned)
        uses: actions/upload-artifact@v4
        with:
          name: SegmentatorAPI-unsigned
          path: dist/segmentator_api.exe
          if-no-files-found: error