name: Build AMIGOpy (unsigned)

on:
  push:
    branches: [ auto_cont ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          python-version: "3.11"
          environment-file: amigo.yml
          activate-environment: amigo

      - name: Upgrade pip
        shell: powershell
        run: python -m pip install --upgrade pip wheel setuptools

      # ---- Minimal deps for AMIGOpy GUI ----
      - name: Install build dependency (PyInstaller for GUI)
        shell: powershell
        run: pip install pyinstaller

      # ---- Build AMIGOpy GUI from your existing spec ----
      - name: PyInstaller (AMIGOpy GUI)
        shell: powershell
        run: pyinstaller Launch_ImGUI.spec --clean

      # ---- Build Windows installers via Inno Setup ----
      - name: Install Inno Setup
        shell: powershell
        run: choco install innosetup -y

      # AMIGOpy installer 
      - name: Build Windows installer (AMIGOpy)
        shell: powershell
        run: '& "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" compile.iss'


      # ---- Upload artifacts ----
      - name: Upload AMIGOpy installer (unsigned)
        uses: actions/upload-artifact@v4
        with:
          name: AMIGOpy-Installer-unsigned
          path: Output/*.exe
          if-no-files-found: error


