name: Build AMIGOpy (GUI + CPU worker) — unsigned

on:
  push:
    branches: [ auto_cont ]
  workflow_dispatch:

jobs:
  build-amigopy:
    runs-on: windows-latest
    env:
      KMP_DUPLICATE_LIB_OK: "TRUE"

    steps:
      - uses: actions/checkout@v4

      - name: Setup Miniconda (builder env)
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          python-version: "3.11"
          environment-file: amigo.yml     # your heavy env
          activate-environment: amigo
          auto-update-conda: true
          channels: conda-forge,defaults

      - name: Add Graphviz to PATH (conda)
        shell: powershell
        run: echo "$env:CONDA_PREFIX\Library\bin" >> $env:GITHUB_PATH

      - name: Upgrade pip tooling
        shell: powershell
        run: python -m pip install --upgrade pip wheel setuptools

      # ---- Pin Torch CPU (no CUDA wheels) ----
      - name: Install PyTorch CPU wheels
        shell: powershell
        run: |
          python -m pip install --upgrade pip
          python -m pip install --index-url https://download.pytorch.org/whl/cpu `
            "torch==2.4.1+cpu" "torchvision==0.19.1+cpu" "torchaudio==2.4.1+cpu"

      - name: Ensure PyInstaller
        shell: powershell
        run: pip install pyinstaller

      - name: Build combined dist (GUI + CPU worker)
        shell: powershell
        run: pyinstaller amigopy.spec --clean

      - name: Verify dist contents
        shell: powershell
        run: |
          if (-not (Test-Path "dist\AMIGOpy\Launch_ImGUI.exe")) { throw "Launch_ImGUI.exe missing" }
          if (-not (Test-Path "dist\AMIGOpy\segmentator_worker.exe")) { throw "segmentator_worker.exe missing" }
          Get-ChildItem -Recurse dist\AMIGOpy | Select-Object -First 40 | Format-List -Property FullName,Length

      - name: Install Inno Setup
        shell: powershell
        run: choco install innosetup -y

      - name: Build AMIGOpy installer
        shell: powershell
        run: '& "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe" AMIGOpy.iss'

      - name: Upload installer (unsigned)
        uses: actions/upload-artifact@v4
        with:
          name: AMIGOpy-Installer-unsigned
          path: Output/AMIGOpy-Setup.exe
          if-no-files-found: error
          overwrite: true
