name: Build AMIGOpy (unsigned)

on:
  push:
    branches: [ auto_cont ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          python-version: "3.11"
          environment-file: amigo.yml
          activate-environment: amigo

      - name: Upgrade pip
        shell: powershell
        run: python -m pip install --upgrade pip wheel setuptools

      # ---- Minimal deps for AMIGOpy GUI ----
      - name: Install build dependency (PyInstaller for GUI)
        shell: powershell
        run: pip install pyinstaller

      - name: PyInstaller (AMIGOpy GUI)
        shell: powershell
        run: pyinstaller Launch_ImGUI.spec --clean

      # ---- Heavy deps only for the API ----
      - name: Install build dependencies (API + TS stack)
        shell: powershell
        run: |
          pip install fastapi uvicorn[standard] starlette pydantic python-multipart
          pip install SimpleITK nibabel scikit-image scipy tqdm einops packaging
          pip install monai==1.* nnunetv2
          pip install --index-url https://download.pytorch.org/whl/cpu torch torchvision
          pip install totalsegmentator

      - name: PyInstaller (Segmentator API, OneDir)
        shell: powershell
        run: pyinstaller segmentator_api.spec --clean

      # ---- Build Windows installers via Inno Setup ----
      - name: Install Inno Setup
        shell: powershell
        run: choco install innosetup -y

      - name: Build Windows installer (AMIGOpy)
        shell: powershell
        run: '& "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" compile.iss'

      - name: Build Windows installer (Segmentator API)
        shell: powershell
        run: '& "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" SegmentatorAPI.iss'

      # ---- Upload exactly one file per artifact (so one file per zip) ----
      - name: Upload AMIGOpy installer (unsigned)
        uses: actions/upload-artifact@v4
        with:
          name: AMIGOpy-Installer-unsigned
          path: Output/mysetup.exe
          if-no-files-found: error
          overwrite: true

      - name: Upload Segmentator API installer (unsigned)
        uses: actions/upload-artifact@v4
        with:
          name: SegmentatorAPI-Installer-unsigned
          path: Output/SegmentatorAPI-Setup.exe
          if-no-files-found: error
          overwrite: true