name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: amigo.yml
          activate-environment: amigo

      - name: Ensure PyInstaller is installed
        run: |
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller Launch_ImGUI.spec

      - name: Install Inno Setup
        run: |
          choco install innosetup -y

      - name: Build Windows installer
        run: |
          '& "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" compile.iss'

      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: AMIGOpy-installer
          path: Output/mysetup.exe
