name: Build AMIGOpy installer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          python-version: "3.11"
          environment-file: amigo.yml
          activate-environment: amigo

      - name: Run PyInstaller
        shell: powershell
        run: |
          pyinstaller Launch_ImGUI.spec

      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Build Windows installer
        run: '& "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" compile.iss'

      - name: Upload unsigned installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-installer
          path: Output/mysetup.exe

  sign-windows-installer:
    needs: build-windows
    runs-on: ubuntu-latest
    steps:
      - name: Download unsigned installer artifact
        uses: actions/download-artifact@v4
        with:
          name: unsigned-installer
          path: .
      - name: Sign Windows installer with SignPath
        uses: signpath/github-action-submit-signing-request@v1.1
        with:
          api-token: ${{ secrets.SIGNPATH_API_TOKEN }}
          organization-id: ${{ secrets.SIGNPATH_ORGANIZATION_ID }}
          project-slug: ${{ secrets.SIGNPATH_PROJECT_SLUG }}
          signing-policy-slug: ${{ secrets.SIGNPATH_SIGNING_POLICY_SLUG }}
          input-artifact-path: 'mysetup.exe'
          wait-for-completion: true
          output-artifact-directory: signed
          
      - name: Upload signed installer
        uses: actions/upload-artifact@v4
        with:
          name: signed-installer
          path: signed/
